# Generated by Django 5.2.14 on 2026-05-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='device_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='page_viewed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='user_agent',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
